import type { Config } from "tailwindcss";

const config: Config = {
  content: ["./src/pages/**/*.{js,ts,jsx,tsx}", "./src/components/**/*.{js,ts,jsx,tsx}", "./src/layouts/**/*.{js,ts,jsx,tsx}"],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#e1e2e4",
        "primary-fixed": "#ffdbca",
        "on-background": "#191c1e",
        "on-error": "#ffffff",
        "outline-variant": "#e0c0b1",
        "on-surface": "#191c1e",
        "on-secondary-fixed": "#141b2b",
        surface: "#f8f9fb",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#783200",
        "inverse-on-surface": "#f0f1f3",
        "on-tertiary-fixed": "#121c2a",
        "surface-container-high": "#e7e8ea",
        "tertiary-container": "#919bad",
        "secondary-fixed": "#dce2f7",
        "surface-container": "#edeef0",
        "surface-dim": "#d9dadc",
        "inverse-surface": "#2e3132",
        "secondary-fixed-dim": "#c0c6db",
        "surface-tint": "#9d4300",
        "secondary-container": "#d9dff5",
        background: "#f8f9fb",
        "inverse-primary": "#ffb690",
        "on-secondary-container": "#5c6274",
        "on-surface-variant": "#584237",
        primary: "#9d4300",
        "tertiary-fixed-dim": "#bdc7d9",
        secondary: "#575e70",
        "surface-bright": "#f8f9fb",
        "on-tertiary": "#ffffff",
        "on-tertiary-container": "#293341",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#e1e2e4",
        "primary-container": "#f97316",
        "on-primary": "#ffffff",
        error: "#ba1a1a",
        "on-secondary-fixed-variant": "#404758",
        "on-tertiary-fixed-variant": "#3d4756",
        "tertiary-fixed": "#d9e3f6",
        "error-container": "#ffdad6",
        "surface-container-low": "#f3f4f6",
        "primary-fixed-dim": "#ffb690",
        "on-error-container": "#93000a",
        "on-primary-fixed": "#341100",
        outline: "#8c7164",
        "on-primary-container": "#582200",
        tertiary: "#555f6f",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        margin: "2rem",
        "space-sm": "0.5rem",
        gutter: "1.5rem",
        "space-lg": "1.5rem",
        "gutter-mobile": "1rem",
        "space-xs": "0.25rem",
        "space-xl": "2.5rem",
        "margin-mobile": "1rem",
        "space-md": "1rem",
      },
      fontFamily: {
        "label-md": ["var(--font-inter)"],
        "display-hero": ["var(--font-plus-jakarta-sans)"],
        "body-lg": ["var(--font-inter)"],
        "display-hero-mobile": ["var(--font-plus-jakarta-sans)"],
        "label-sm": ["var(--font-inter)"],
        "body-sm": ["var(--font-inter)"],
        "headline-lg-mobile": ["var(--font-plus-jakarta-sans)"],
        "headline-md": ["var(--font-plus-jakarta-sans)"],
        "body-md": ["var(--font-inter)"],
        "headline-lg": ["var(--font-plus-jakarta-sans)"],
        "title-sm": ["var(--font-plus-jakarta-sans)"],
        "label-urgency": ["var(--font-plus-jakarta-sans)"],
        "headline-xl-mobile": ["var(--font-plus-jakarta-sans)"],
        "mono-data": ["var(--font-inter)"],
        "headline-xl": ["var(--font-plus-jakarta-sans)"],
      },
      fontSize: {
        "label-md": ["14px", { lineHeight: "18px", fontWeight: "600" }],
        "display-hero": ["56px", { lineHeight: "64px", letterSpacing: "-0.03em", fontWeight: "800" }],
        "body-lg": ["18px", { lineHeight: "28px", fontWeight: "400" }],
        "display-hero-mobile": ["36px", { lineHeight: "42px", letterSpacing: "-0.02em", fontWeight: "800" }],
        "label-sm": ["12px", { lineHeight: "16px", fontWeight: "500" }],
        "body-sm": ["14px", { lineHeight: "20px", fontWeight: "400" }],
        "headline-lg-mobile": ["24px", { lineHeight: "30px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "headline-md": ["22px", { lineHeight: "28px", fontWeight: "600" }],
        "body-md": ["16px", { lineHeight: "24px", fontWeight: "400" }],
        "headline-lg": ["30px", { lineHeight: "38px", letterSpacing: "-0.015em", fontWeight: "700" }],
        "title-sm": ["18px", { lineHeight: "24px", fontWeight: "600" }],
        "label-urgency": ["13px", { lineHeight: "16px", letterSpacing: "0.06em", fontWeight: "800" }],
        "headline-xl-mobile": ["28px", { lineHeight: "34px", letterSpacing: "-0.01em", fontWeight: "700" }],
        "mono-data": ["15px", { lineHeight: "20px", letterSpacing: "0.02em", fontWeight: "700" }],
        "headline-xl": ["40px", { lineHeight: "48px", letterSpacing: "-0.02em", fontWeight: "700" }],
      },
    },
  },
  plugins: [],
};

export default config;
